services:
  - type: web
    plan: free
    name: alpher_file_store_bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    repo: https://github.com/v15hnuf6n1x/File-Storing.git      
    branch: V1.2
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH
        sync: false
      - key: ADMINS
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: DATABASE_URI
        sync: false 
      - key: PICS
        sync: false
      - key: LOG_CHANNEL
        sync: false    
    autoDeploy: false
